#!/usr/bin/env python3
"""Regenerates src/PinPresets.h: the built-in pin pictures (the "BowlingPlus collection" in the pin library),
embedded as PNG bytes for both platforms (iOS OilUI.mm, Android Jni.cpp N.bytes("preset:<id>")).
Each preset is a picture in either layout BowlingPlus accepts (a 2:1 wrap sheet is best; 4096 x 2048 gives the
sharpest 2048 px pin). Opaque pictures are stored as RGB PNG (smaller); BowlingPlus draws on white anyway.
Usage (from the repo root):  python3 tools/dev/make_pin_presets.py"""
import io, os
from PIL import Image
PRESETS = [   # (id, name, subtitle, file)
    ('crownmax', 'Brunswick Max Crown', 'Brunswick \u00b7 wrap picture', 'pins/BrunswickCrownMax.png'),
]
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '../..')
out = ['// Generated by tools/dev/make_pin_presets.py from pins/. Do not edit by hand.',
       '// The built-in pin pictures (the pin library\'s "BowlingPlus collection").', '#pragma once', '']
table = []
for pid, name, sub, path in PRESETS:
    im = Image.open(os.path.join(root, path))
    if im.mode == 'RGBA' and im.getchannel('A').getextrema() == (255, 255): im = im.convert('RGB')
    b = io.BytesIO(); im.save(b, 'PNG', optimize=True); data = b.getvalue()
    sym = 'kBPPinPreset_' + pid
    out.append('static const unsigned char %s[] = {' % sym)
    for i in range(0, len(data), 24):
        out.append('    ' + ', '.join('0x%02x' % x for x in data[i:i + 24]) + ',')
    out.append('};')
    out.append('static const unsigned int %sLen = %d;   // %s, %d x %d' % (sym, len(data), path, im.size[0], im.size[1]))
    out.append('')
    table.append('    { "%s", "%s", "%s", %s, %sLen },' % (pid, name.replace('"', '\\"'), sub, sym, sym))
out += ['struct BPPinPreset { const char *id, *name, *sub; const unsigned char *png; unsigned int len; };',
        'static const BPPinPreset kBPPinPresets[] = {'] + table + ['};',
        'static const int kBPPinPresetCount = (int)(sizeof(kBPPinPresets) / sizeof(kBPPinPresets[0]));', '']
open(os.path.join(root, 'src/PinPresets.h'), 'w', encoding='utf-8').write('\n'.join(out))
print('src/PinPresets.h: %d preset(s)' % len(PRESETS))
