#!/usr/bin/env python3
# Turn a binary file (the Java side's classes.dex) into a C header the native library embeds, so the whole
# tweak is one libmain.so with no separate dex file to ship.
#   bin2header.py <input> <symbol> <output.h>
import sys

def main():
    if len(sys.argv) != 4:
        print("usage: bin2header.py <input> <symbol> <output.h>", file=sys.stderr)
        sys.exit(1)
    inp, sym, out = sys.argv[1], sys.argv[2], sys.argv[3]
    with open(inp, "rb") as f:
        data = f.read()
    with open(out, "w") as f:
        f.write("// Generated by bin2header.py - do not edit.\n#pragma once\n")
        f.write("static const unsigned char %s[] = {\n" % sym)
        for i in range(0, len(data), 16):
            f.write("  " + ",".join("0x%02x" % b for b in data[i:i + 16]) + ",\n")
        f.write("};\n")
        f.write("static const unsigned int %sLen = %dU;\n" % (sym, len(data)))
    print("%s: %d bytes -> %s" % (inp, len(data), out))

if __name__ == "__main__":
    main()
